sudo: request
services:
  - docker

before_install:
  - docker build -t dockerimage -f Dockerfile.dev .

script:
  - docker run -e CI=true dockerimage python -m pytest

deploy:
  provider: heroku

  on:
    branch: master

  api_key:
    secure: $HEROKU_API_KEY
    app: dothistory
