FROM python:3.8.3-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT development
ENV TESTING true
ENV DATABASE_URL postgres://postgres:postgres@postgres-db:5432/dev_db
ENV DATABASE_URL_TEST ostgres://postgres:postgres@postgres-db:5432/test_db

RUN apt-get update \
    && apt-get -y install netcat gcc \
    && apt-get clean

RUN pip install --upgrade pip

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

