version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    environment:
      - ENVIRONMENT=development
      - TESTING=FALSE
    command: uvicorn project.app.main:app --port 5000 --host 0.0.0.0 --reload
