version: '3'
services:
  web:
    build:
      context: ./project/app
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    command: uvicorn project.app.main:app --port 5000 --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres-db

  postgres-db:
    build:
      context: ./project/db
    expose:
      - 5432
